site_name: Prisma Flow
site_url: https://osl-incubator.github.io/prisma-flow
repo_url: https://github.com/osl-incubator/prisma-flow
repo_name: osl-incubator/prisma-flow
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./build

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      provider: github
      repo_url_shortener: true
  - pymdownx.saneheaders
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Changelog: changelog.md

extra:
  project_name: "Prisma Flow"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/osl-incubator/prisma-flow
      name: Prisma Flow on GitHub

copyright: "Copyright &copy; 2026, Open Science Labs Incubator"
