blank_issues_enabled: true
contact_links:
  - name: 🙋  Usage Questions
    url: https://github.com/osl-incubator/prisma-flow/discussions
    about: Use GitHub Discussions for questions and design conversations.
  - name: 📝  Prisma Flow Code of Conduct
    url: https://github.com/osl-incubator/prisma-flow/blob/main/CODE_OF_CONDUCT.md
    about: Expectations for how contributors interact with each other.
