"""
title: Pure-Python SVG renderer.
"""

from __future__ import annotations

from html import escape

from prismaflow.layout.engine import DiagramEdge, DiagramLayout, DiagramNode
from prismaflow.layout.geometry import Point
from prismaflow.layout.text import wrap_text


class SVGRenderer:
    """
    title: Render diagram layouts to dependency-free SVG.
    attributes:
      font_family:
        description: CSS font-family used for SVG text.
      font_size:
        description: Base SVG text size in pixels.
      line_height:
        description: Distance between wrapped text lines in pixels.
    """

    def __init__(
        self,
        *,
        font_family: str = "Arial, Helvetica, sans-serif",
        font_size: int = 14,
        line_height: int = 17,
    ) -> None:
        """
        title: Configure SVG font and line spacing.
        parameters:
          font_family:
            type: str
            description: Value for font_family.
          font_size:
            type: int
            description: Value for font_size.
          line_height:
            type: int
            description: Value for line_height.
        """
        self.font_family = font_family
        self.font_size = font_size
        self.line_height = line_height

    def render(self, layout: DiagramLayout) -> str:
        """
        title: Render a diagram layout to SVG text.
        parameters:
          layout:
            type: DiagramLayout
            description: Value for layout.
        returns:
          type: str
          description: Return value.
        """
        title = layout.title or "PRISMA flow diagram"
        desc = "PRISMA-style flow diagram generated by prisma-flow."
        parts = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            (
                f'<svg xmlns="http://www.w3.org/2000/svg" '
                f'width="{layout.width:g}" height="{layout.height:g}" '
                f'viewBox="0 0 {layout.width:g} {layout.height:g}" '
                'role="img" aria-labelledby="title desc">'
            ),
            f'<title id="title">{escape(title)}</title>',
            f'<desc id="desc">{escape(desc)}</desc>',
            self._defs(),
            self._style(),
        ]

        if layout.title:
            parts.append(
                f'<text class="diagram-title" x="{layout.width / 2:g}" y="42">'
                f"{escape(layout.title)}</text>"
            )

        parts.append('<g class="edges">')
        parts.extend(self._render_edge(layout, edge) for edge in layout.edges)
        parts.append("</g>")

        parts.append('<g class="nodes">')
        parts.extend(self._render_node(node) for node in layout.nodes)
        parts.append("</g>")
        parts.append("</svg>")
        return "\n".join(parts) + "\n"

    def _defs(self) -> str:
        """
        title: _defs.
        returns:
          type: str
          description: Return value.
        """
        return """
<defs>
  <marker id="arrowhead" markerWidth="10" markerHeight="7"
          refX="9" refY="3.5" orient="auto">
    <polygon points="0 0, 10 3.5, 0 7" />
  </marker>
</defs>""".strip()

    def _style(self) -> str:
        """
        title: _style.
        returns:
          type: str
          description: Return value.
        """
        return f"""
<style>
  svg {{ background: #ffffff; color: #111827; }}
  .diagram-title {{
    font-family: {self.font_family};
    font-size: 22px;
    font-weight: 700;
    text-anchor: middle;
    fill: #111827;
  }}
  .node rect {{
    fill: #ffffff;
    stroke: #1f2937;
    stroke-width: 1.5;
    rx: 4;
    ry: 4;
  }}
  .node.exclusion rect {{ fill: #f9fafb; stroke: #4b5563; }}
  .node text {{
    font-family: {self.font_family};
    font-size: {self.font_size}px;
    text-anchor: middle;
    dominant-baseline: middle;
    fill: #111827;
  }}
  .edge {{
    fill: none;
    stroke: #1f2937;
    stroke-width: 1.6;
    marker-end: url(#arrowhead);
  }}
  marker polygon {{ fill: #1f2937; }}
</style>""".strip()

    def _render_node(self, node: DiagramNode) -> str:
        """
        title: _render_node.
        parameters:
          node:
            type: DiagramNode
            description: Value for node.
        returns:
          type: str
          description: Return value.
        """
        css_parts = ["node", node.kind]
        if node.css_class:
            css_parts.append(node.css_class)
        css_class = " ".join(css_parts)
        rect = node.rect
        href_start = f'<a href="{escape(node.href)}">' if node.href else ""
        href_end = "</a>" if node.href else ""
        title = f"<title>{escape(node.tooltip)}</title>\n" if node.tooltip else ""
        text_lines = wrap_text(node.text, max_chars=max(18, int(rect.width / 8)))
        text = self._render_text(rect.center_x, rect.center_y, text_lines)
        return (
            f'{href_start}<g id="{escape(node.id)}" class="{css_class}">\n'
            f"{title}"
            f'  <rect x="{rect.x:g}" y="{rect.y:g}" '
            f'width="{rect.width:g}" height="{rect.height:g}" />\n'
            f"{text}\n"
            f"</g>{href_end}"
        )

    def _render_text(self, x: float, y: float, lines: list[str]) -> str:
        """
        title: _render_text.
        parameters:
          x:
            type: float
            description: Value for x.
          y:
            type: float
            description: Value for y.
          lines:
            type: list[str]
            description: Value for lines.
        returns:
          type: str
          description: Return value.
        """
        line_count = len(lines)
        start_y = y - ((line_count - 1) * self.line_height / 2)
        tspans = []
        for index, line in enumerate(lines):
            dy = 0 if index == 0 else self.line_height
            tspans.append(f'    <tspan x="{x:g}" dy="{dy:g}">{escape(line)}</tspan>')
        return (
            f'  <text x="{x:g}" y="{start_y:g}">\n' + "\n".join(tspans) + "\n  </text>"
        )

    def _render_edge(self, layout: DiagramLayout, edge: DiagramEdge) -> str:
        """
        title: _render_edge.
        parameters:
          layout:
            type: DiagramLayout
            description: Value for layout.
          edge:
            type: DiagramEdge
            description: Value for edge.
        returns:
          type: str
          description: Return value.
        """
        points = self._edge_points(layout, edge)
        path = " ".join(
            [f"M {points[0].x:g} {points[0].y:g}"]
            + [f"L {point.x:g} {point.y:g}" for point in points[1:]]
        )
        css_class = "edge" + (f" {edge.css_class}" if edge.css_class else "")
        return (
            f'<path id="{escape(edge.id)}" class="{css_class}" d="{path}" '
            'marker-end="url(#arrowhead)" />'
        )

    @staticmethod
    def _edge_points(layout: DiagramLayout, edge: DiagramEdge) -> list[Point]:
        """
        title: _edge_points.
        parameters:
          layout:
            type: DiagramLayout
            description: Value for layout.
          edge:
            type: DiagramEdge
            description: Value for edge.
        returns:
          type: list[Point]
          description: Return value.
        """
        if edge.path:
            return edge.path
        source = layout.node_by_id(edge.source_id).rect.anchor(edge.source_anchor)
        target = layout.node_by_id(edge.target_id).rect.anchor(edge.target_anchor)
        if source.x == target.x or source.y == target.y:
            return [source, target]
        if edge.source_anchor in {"top", "bottom"}:
            mid_y = (source.y + target.y) / 2
            return [source, Point(source.x, mid_y), Point(target.x, mid_y), target]
        mid_x = (source.x + target.x) / 2
        return [source, Point(mid_x, source.y), Point(mid_x, target.y), target]
