name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  VIRTUALENV_ACTIVATORS: "bash,python"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/release.yaml
          channels: conda-forge,nodefaults
          activate-environment: prismaflow
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.13"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry check
          poetry install --extras "dev yaml"

      - name: Run release dry-run
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: makim release.dry

      - name: Run semantic release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "${PYPI_TOKEN}"
          makim release.ci
